In [136]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import copy

In [2]:
stock_prices = [10, 7, 5, 8, 11, 9]

prices = np.asarray(stock_prices);

In [10]:
min_price = min(prices)
max_price = max(prices)

In [15]:
asdf = np.max(diff)
type(asdf)

index = np.where(diff==asdf)
print(index)


(array([2], dtype=int64), array([4], dtype=int64))


In [16]:
def max_sale(data):
    N = len(data)
    diff = np.zeros((N,N))
    for i in range(0,N,1):
        for j in range(i,N,1):
            diff[i][j] = data[j] - data[i]
    diff_max = np.max(diff)
    max_index = np.where(diff ==diff_max)
    return diff, diff_max, max_index

In [19]:
diff, maxsale, maxindex = max_sale(prices)
print(diff)
print(maxsale)
print(maxindex)

[[ 0. -3. -5. -2.  1. -1.]
 [ 0.  0. -2.  1.  4.  2.]
 [ 0.  0.  0.  3.  6.  4.]
 [ 0.  0.  0.  0.  3.  1.]
 [ 0.  0.  0.  0.  0. -2.]
 [ 0.  0.  0.  0.  0.  0.]]
6.0
(array([2], dtype=int64), array([4], dtype=int64))


In [27]:
diff[2][2]

0.0

In [ ]:
def profit(prices):
    max_px = 0
    min_px = prices[0]
    for px in prices[1:]:
        min_px = min(min_px, px)
        max_px = max(px - min_px, max_px)
    return max_px

prices = (20, 18, 14, 17, 20, 21, 15)
profit(prices)

In [134]:
a = [0] * 20
print(a)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [137]:
b = copy.deepcopy(a)

In [139]:

A  = np.array([1,2,3,4])