In [251]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from collections import defaultdict, Counter
import random
import time
from collections import defaultdict
from __future__ import division
from scipy import stats

In [141]:
empty_dict = {}

In [142]:
f=time.strftime('%H')
f=int(f)

if f < 12:
    print('Good morning, Matt!')
elif 12 <= f < 16:
    print('Good afternoon, Matt!')
else:
    print('Good evening, Matt!')   

Good morning, Matt!


In [5]:
grades = {"Joel" : 80, "Tim" : 95}

In [7]:
grades

{'Joel': 80, 'Tim': 95}

In [11]:
joels_grade = grades["Joel"]
print joels_grade

80


In [13]:
print(joels_grade)

80


In [14]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
grades.get("Joel")

80

In [22]:
dict.get?

In [24]:
novalues = grades.get("Kate")
print(novalues)

None


In [25]:
2 + \
3

5

In [28]:
grades.keys()

['Tim', 'Joel']

In [29]:
type(grades)

dict

In [32]:
grades.size

AttributeError: 'dict' object has no attribute 'size'

In [33]:
set('tiger')

{'e', 'g', 'i', 'r', 't'}

In [35]:
from collections import Counter

In [36]:
c = Counter([0, 1, 2, 0])

In [37]:
c

Counter({0: 2, 1: 1, 2: 1})

In [38]:
s = set()

In [39]:
s.add(1)

In [40]:
s

{1}

In [41]:
y = 1 in s

In [42]:
y

True

In [43]:
type(y)

bool

In [47]:
x =  [4, 1, 2, 3]

In [50]:
x.sort(reverse=True)

In [51]:
x

[4, 3, 2, 1]

In [57]:
z = [random.random() for itemslist in range(4)]
print(z)

[0.028141736515415627, 0.7536752335998025, 0.6255395726333427, 0.06174423455833078]


In [58]:
zl = {random.random() for itemslist in range(4)
print(zl)

set([0.8309679740974204, 0.12449515402321731, 0.5456038548357807, 0.630514811106433])


In [59]:
zd = dict(random.random() for itemslist in range(4))
print(zd)

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [60]:
dict?

In [64]:
s.add?

In [71]:
interests = [(0, 'apples'),(0, 'oranges'),(1, 'apples'),(2, 'limes'), (2, 'apples'),(3, 'lemons'),(3, 'apples')]

In [72]:
interests

[(0, 'apples'),
 (0, 'oranges'),
 (1, 'apples'),
 (2, 'limes'),
 (2, 'apples'),
 (3, 'lemons'),
 (3, 'apples')]

In [73]:
words_and_counts = Counter(word 
                           for user, interest in interests 
                           for word in interest.lower().split())

In [76]:
for word, count in words_and_counts.most_common():
    if count > 1:
        print word, count

apples 4


In [78]:
Counter?

In [81]:
words_and_counts.most_common()  #if number, n, inserted in .most_common(), lists n-many elements in descending order of frequency. if left blank, lists all in frequency.

[('apples', 4), ('lemons', 1), ('oranges', 1), ('limes', 1)]

In [82]:
sorted(words_and_counts)  #lists all unique elements

['apples', 'lemons', 'limes', 'oranges']

In [88]:
words_and_counts.values()

[1, 4, 1, 1]

In [87]:
sorted(words_and_counts.values(),reverse=True)

[4, 1, 1, 1]

In [89]:
words_and_counts['apples']

4

In [90]:
my_tuple = (1,2,3)

In [91]:
type(my_tuple)

tuple

In [92]:
my_tuple[0] = 1

TypeError: 'tuple' object does not support item assignment

In [94]:
try: 
    my_tuple[0] = 2;
except TypeError:
    print "can't touch this!"

can't touch this!


In [136]:
x = [1,2,3];y=[4,5,6]

In [96]:
np.concatenate(x,y)

TypeError: 'list' object cannot be interpreted as an index

In [97]:
np.concatenate?

In [98]:
npx = np.asarray(x); #can do this because lists are homogeenous (in this case integers)

In [99]:
npy = np.asarray(y); #can do this because lists are homogeenous (in this case integers)

In [105]:
npxy = np.concatenate((npx,npy))

In [103]:
type(npx)

numpy.ndarray

In [106]:
npxy

array([1, 2, 3, 4, 5, 6])

In [137]:
z = x + y

In [138]:
z

[1, 2, 3, 4, 5, 6]

In [180]:
f = open('98-0.txt')#, errors='ignore')
g = f.read().lower().split()
h = dict(enumerate(g))
f.close
word_counts = Counter(g)
word_counts.most_common()

[('the', 8106),
 ('and', 4836),
 ('of', 4093),
 ('to', 3491),
 ('a', 2946),
 ('in', 2546),
 ('his', 1979),
 ('he', 1751),
 ('that', 1704),
 ('was', 1678),
 ('i', 1446),
 ('it', 1408),
 ('with', 1323),
 ('had', 1270),
 ('as', 1113),
 ('at', 1018),
 ('you', 1010),
 ('for', 901),
 ('her', 853),
 ('on', 851),
 ('not', 779),
 ('is', 734),
 ('have', 714),
 ('be', 708),
 ('were', 633),
 ('my', 605),
 ('mr.', 602),
 ('said', 570),
 ('by', 558),
 ('they', 538),
 ('him', 527),
 ('this', 520),
 ('from', 520),
 ('all', 495),
 ('so', 454),
 ('but', 454),
 ('no', 450),
 ('or', 426),
 ('she', 424),
 ('when', 420),
 ('been', 415),
 ('if', 408),
 ('\xe2\x80\x9ci', 400),
 ('which', 382),
 ('there', 378),
 ('one', 364),
 ('an', 345),
 ('who', 345),
 ('out', 338),
 ('would', 330),
 ('your', 328),
 ('their', 317),
 ('into', 316),
 ('are', 309),
 ('what', 290),
 ('upon', 281),
 ('me', 272),
 ('could', 266),
 ('will', 261),
 ('little', 253),
 ('any', 250),
 ('up', 248),
 ('do', 235),
 ('it,', 231),
 ('its', 

In [184]:
h.items()

[(0, '\xef\xbb\xbfthe'),
 (1, 'project'),
 (2, 'gutenberg'),
 (3, 'ebook'),
 (4, 'of'),
 (5, 'a'),
 (6, 'tale'),
 (7, 'of'),
 (8, 'two'),
 (9, 'cities,'),
 (10, 'by'),
 (11, 'charles'),
 (12, 'dickens'),
 (13, 'this'),
 (14, 'ebook'),
 (15, 'is'),
 (16, 'for'),
 (17, 'the'),
 (18, 'use'),
 (19, 'of'),
 (20, 'anyone'),
 (21, 'anywhere'),
 (22, 'at'),
 (23, 'no'),
 (24, 'cost'),
 (25, 'and'),
 (26, 'with'),
 (27, 'almost'),
 (28, 'no'),
 (29, 'restrictions'),
 (30, 'whatsoever.'),
 (31, 'you'),
 (32, 'may'),
 (33, 'copy'),
 (34, 'it,'),
 (35, 'give'),
 (36, 'it'),
 (37, 'away'),
 (38, 'or'),
 (39, 're-use'),
 (40, 'it'),
 (41, 'under'),
 (42, 'the'),
 (43, 'terms'),
 (44, 'of'),
 (45, 'the'),
 (46, 'project'),
 (47, 'gutenberg'),
 (48, 'license'),
 (49, 'included'),
 (50, 'with'),
 (51, 'this'),
 (52, 'ebook'),
 (53, 'or'),
 (54, 'online'),
 (55, 'at'),
 (56, 'www.gutenberg.org'),
 (57, 'title:'),
 (58, 'a'),
 (59, 'tale'),
 (60, 'of'),
 (61, 'two'),
 (62, 'cities'),
 (63, 'a'),
 (64, 's

In [187]:
int_dict = defaultdict(int)

In [189]:
print(int_dict)

defaultdict(<type 'int'>, {})


In [190]:
newdict = defaultdict(dict)

In [192]:
newdict["Joel"]["City"] = "Seattle"

In [193]:
newdict

defaultdict(dict, {'Joel': {'City': 'Seattle'}})

In [199]:
even_numbers = [x for x in range(5) if x %2==0]

In [200]:
even_numbers

[0, 2, 4]

In [201]:
even_squares = [x*x for x in even_numbers]

In [202]:
even_squares

[0, 4, 16]

In [203]:
A = [[1,2,3],[4,5,6],[7,8,9]]

In [204]:
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [207]:
A[1][1]

5

In [209]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [212]:
x = [92.0,84.0,99.0,96.0,88.0,78.0,97.0]

In [222]:
sum(x)/len(x)

90.57142857142857

In [216]:
np.mean(x)

90.57142857142857

In [228]:
np.median(x)

92.0

In [234]:
np.quantile(x,.50) ##this is actually just the median

92.0

In [235]:
np.quantile(x,.25)

86.0

In [236]:
np.quantile(x,.75)

96.5

In [249]:
print("The Interquantile range is {}.".format(np.quantile(x,.75) - np.quantile(x,.25)))

The Interquantile range is 10.5.


In [242]:
np.quantile(x,.75) - np.quantile(x,.25)

10.5

In [250]:
np.mode(x)

AttributeError: 'module' object has no attribute 'mode'

In [252]:
stats.mode(x)

ModeResult(mode=array([78.]), count=array([1]))

In [257]:
xrange = max(x) - min(x)
print(xrange)

21.0


In [354]:
def x_stats(x):
    x_mean = np.mean(x);
    N = len(x);
    a = range(N);
    for i in range(N):
        a[i] = (x[i] - x_mean)**2;
    sum_square_diff = sum(a);
    x_var = 1./N * sum_square_diff;
    return x_mean, x_var 

In [355]:
xmean, xvar = x_stats(x)

In [356]:
print(xmean,xvar)

(90.57142857142857, 50.24489795918368)


In [328]:
print(np.var(x))
print(np.std(x))

50.24489795918368
7.0883635600315875


In [326]:
xstd = np.sqrt(x_var_function(x))
print(xstd)

7.0883635600315875


In [329]:
x.index(99)

2

In [313]:
variance_of_data

NameError: name 'variance_of_data' is not defined

[]

In [334]:
npxary = np.linspace(0,10,11)
print(npxary)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [343]:
npxary.std()

3.1622776601683795

In [344]:
np.var(npxary)

10.0

In [291]:
np.var?

In [292]:
len(x)

7

In [266]:
sum(x)

634.0

In [269]:
N = len(x)
print(N)

7


In [270]:
mean_x= np.mean(x)

In [ ]:
(x(i))

In [426]:
array_of_numbers = np.array([0.5, -6.0, -2.1, 3.78, 9.2, 17.0, -11.2]);

In [431]:
N = len(array_of_numbers);
delta_vals = np.empty((N-1,N-1))
delta_vals[:] = np.nan;

In [432]:
for j in range(0,N-2,1):
    for i in range(j+1,N-1,1):
        delta_vals[j,i] = abs(array_of_numbers[j] - array_of_numbers[i])

In [433]:
delta_vals

array([[  nan,  6.5 ,  2.6 ,  3.28,  8.7 , 16.5 ],
       [  nan,   nan,  3.9 ,  9.78, 15.2 , 23.  ],
       [  nan,   nan,   nan,  5.88, 11.3 , 19.1 ],
       [  nan,   nan,   nan,   nan,  5.42, 13.22],
       [  nan,   nan,   nan,   nan,   nan,  7.8 ],
       [  nan,   nan,   nan,   nan,   nan,   nan]])

In [435]:
np.nanmin(delta_vals)

2.6

In [436]:
delta_min = np.where(delta_vals==np.nanmin(delta_vals))
print(delta_min)

(array([0], dtype=int64), array([2], dtype=int64))


In [441]:
def multiply(a,b):
    mult_value = a*b
    return mult_value

In [442]:
multiply(10,2)

20

In [444]:
np.log10(100)

2.0